---
apiVersion: v2
appVersion: "2.7.12"
description: NetBox is an open source web application designed to help manage and document computer networks.
name: netbox
version: 1.0.1
icon: https://github.com/netbox-community/netbox/raw/develop/docs/netbox_logo.svg?sanitize=true
home: https://netbox.readthedocs.io/en/stable/
sources:
  - https://github.com/enix/helm-charts/tree/master/charts/netbox
  - https://github.com/netbox-community/netbox
  - https://github.com/netbox-community/netbox-docker
dependencies:
  - name: postgresql
    version: '>=8.7.3'
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: '>=10.6.3'
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
maintainers:
  - name: Antoine Millet
    email: antoine@inaps.org
    url: https://github.com/NaPs