---
apiVersion: v2
appVersion: "2.5.2"
description: A Helm chart for Netbox
name: netbox
version: 0.1.1
icon: https://github.com/netbox-community/netbox/raw/develop/docs/netbox_logo.svg?sanitize=true
home: https://netbox.readthedocs.io/en/stable/
sources:
  - https://github.com/enix/helm-charts/tree/master/charts/netbox
  - https://github.com/netbox-community/netbox
  - https://github.com/netbox-community/netbox-docker
dependencies:
  - name: postgresql
    version: '>=3.9.1'
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: redis
    version: '>=9.1.2'
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: redis.enabled