apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-monitoring-proxy.fullname" . }}
  labels:
    {{- include "rancher-monitoring-proxy.labels" . | nindent 4 }}
    {{- with .Values.service.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rancher-monitoring-proxy.selectorLabels" . | nindent 4 }}
