apiVersion: v2
name: kube-router
description: A turnkey solution for Kubernetes networking with aim to provide operational simplicity and high performance.
type: application
version: 1.2.0
appVersion: v1.1.1

icon: https://cdn.rawgit.com/cloudnativelabs/kube-router/64f7700e/Documentation/img/logo-full.svg
home: https://www.kube-router.io/
sources:
  - https://github.com/enix/helm-charts/tree/master/charts/kube-router
  - https://github.com/cloudnativelabs/kube-router
maintainers:
  - name: Enix
    email: contact@enix.fr
    url: https://github.com/enixsas
  - name: Antoine Millet
    email: antoine@inaps.org
    url: https://github.com/NaPs
  - name: Alexandre Buisine
    email: alexandre.buisine@enix.fr
    url: https://github.com/abuisine
annotations:
  artifacthub.io/images: |
    - name: img1
      image: cloudnativelabs/kube-router:v1.1.1
  artifacthub.io/changes: |
    - fix(nrc): multiple services with the same VIP
    - remove deprecated netpol beta API support
    - Update golang.org/x/net dependency
    - Update to golang 1.15 and alpine-3.12
    - Update bgp.md
    - Cleanup non-DSR externalIPs