kind: Deployment
apiVersion: apps/v1
metadata:
  name: dothill-controller-server
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: dynamic-provisionning-controller
{{ include "dothill.labels" . | indent 4 }}

spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dothill-controller-server
{{ include "dothill.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app: dothill-controller-server
{{ include "dothill.labels" . | indent 8 }}
    spec:
      serviceAccount: csi-provisioner
      containers:
        - name: dothill-controller
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          command:
            - dothill-controller
            - -bind=unix:///csi/csi.sock
{{- include "dothill.extraArgs" .Values.controller | indent 10 }}
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-provisioner
          image: {{ .Values.csiProvisioner.image.repository }}:{{ .Values.csiProvisioner.image.tag }}
          args:
            - --csi-address=/csi/csi.sock
            - --worker-threads=1
            - --timeout={{ .Values.csiProvisioner.timeout }}
{{- include "dothill.extraArgs" .Values.csiProvisioner | indent 10 }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-attacher
          image: {{ .Values.csiAttacher.image.repository }}:{{ .Values.csiAttacher.image.tag }}
          args:
            - --csi-address=/csi/csi.sock
            - --worker-threads=1
            - --timeout={{ .Values.csiAttacher.timeout }}
{{- include "dothill.extraArgs" .Values.csiAttacher | indent 10 }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: csi-resizer
          image: {{ .Values.csiResizer.image.repository }}:{{ .Values.csiResizer.image.tag }}
          args:
            - --csi-address=/csi/csi.sock
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
      volumes:
        - name: socket-dir
          emptyDir:
            medium: Memory
