apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.class }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/component: httpd
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80