{{- if and .Values.rbac.create .Values.rbacProxy.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "x509-exporter.serviceAccountName" . }}
  labels:
    {{- include "x509-exporter.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{ . | toYaml | trim | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "x509-exporter.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "x509-exporter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
