apiVersion: v1
kind: Service
metadata:
  name: {{ include "x509-exporter.fullname" . }}
  labels:
    {{- include "x509-exporter.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{ . | toYaml | trim | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.servicePort }}
      targetPort: metrics
  selector:
    {{- include "x509-exporter.selectorLabels" . | nindent 4 }}
