{{- if .Values.rbacProxy.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "x509-exporter.fullname" . }}
  labels:
    {{- include "x509-exporter.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{ . | toYaml | trim | nindent 4 }}
    {{- end }}
{{- end }}
