apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "swift-exporter.fullname" . }}
  labels:
    {{- include "swift-exporter.labels" . | nindent 4 }}
  {{- with .Values.extraLabels }}
    {{- . | toYaml | trim | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "swift-exporter.selectorLabels" . | nindent 6 }}
{{- with .Values.swiftExporter.replicas }}
  replicas: {{ . }}
{{- end }}
  template:
    metadata:
      labels:
        {{- include "swift-exporter.selectorLabels" . | nindent 8 }}
      {{- with .Values.podExtraLabels }}
        {{- . | toYaml | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.swiftExporter.podExtraLabels }}
        {{- . | toYaml | trim | nindent 8 }}
      {{- end }}
    {{- if or .Values.podAnnotations .Values.swiftExporter.podAnnotations }}
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
      {{- with .Values.swiftExporter.podAnnotations }}
        {{- toYaml . | trim | nindent 8 }}
      {{- end }}
    {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.swiftExporter.securityContext }}
          securityContext:
            {{- toYaml . | trim | nindent 12 }}
        {{- end }}
        {{- with .Values.swiftExporter.resources }}
          resources:
          {{- . | toYaml | trim | nindent 12 }}
        {{- end }}
          image: {{ include "swift-exporter.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SWIFT_AUTH_URL
              value: "{{ .Values.swift.url }}"
            - name: SWIFT_USERNAME
              value: "{{ .Values.swift.usr }}"
            - name: SWIFT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: swift-auth
                  key: password
            - name: SWIFT_DOMAIN_NAME
              value: "{{ .Values.swift.domain }}" 
            - name: SWIFT_PROJECT_NAME
              value: "{{ .Values.swift.project }}"
            - name: SWIFT_PROJECT_DOMAINE_NAME
              value: "{{ .Values.swift.project_domain }}"
            - name: EXPORTER_TIMOUT_SEC
              value: "{{ .Values.exporter.timeout }}"
            - name: EXPORTER_REQUEST_RATE_SEC
              value: "{{ .Values.exporter.request_rate }}"
          ports:
            - name: merics
              containerPort: {{ .Values.podListenPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.podListenPort }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.podListenPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
