# Default values for QCOW provisioner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

kubeletPath: /var/lib/kubelet
verbosity: 4
maxVolumesPerNode: 256
ports:
  node: 22420
  ssh: 22421

image:
  repository: docker-registry.enix.io/products/qcow-provisioner
  tag: master
  pullSecret: regcred

csiProvisioner:
  image:
    repository: quay.io/k8scsi/csi-provisioner
    tag: v2.1.0

csiAttacher:
  image:
    repository: quay.io/k8scsi/csi-attacher
    tag: v2.2.1

csiNodeRegistrar:
  extraArgs:
    - --v=5
  image:
    repository: quay.io/k8scsi/csi-node-driver-registrar
    tag: v2.1.0

nodeLivenessProbe:
  image:
    repository: k8s.gcr.io/sig-storage/livenessprobe
    tag: v2.1.0

storageClasses:
  - name: qcow.csi.enix.io
