apiVersion: v1
kind: ConfigMap
metadata:
  name: init-node
data:
  init-node.sh: |- {{ range .Files.Lines "init-iscsi.sh" }}
    {{ . }}{{ end }}
  multipath.conf: |- {{ range .Files.Lines "multipath.conf" }}
    {{ . }}{{ end }}
