{{- range .Values.storageClasses -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .name }}

provisioner: dothill.csi.enix.io
parameters:
  pool: {{ .pool }}
  fsType: {{ .fsType }}
  iqn: {{ .iqn }}
  portals: {{ .portals }}

  csi.storage.k8s.io/provisioner-secret-name: {{ $.Release.Name }}-{{ .secretName }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $.Release.Namespace }}
  csi.storage.k8s.io/controller-publish-secret-name: {{ $.Release.Name }}-{{ .secretName }}
  csi.storage.k8s.io/controller-publish-secret-namespace: {{ $.Release.Namespace }}
---
{{- end -}}

{{- range $key, $value := .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $key }}

type: Opaque
data:
{{ toYaml $value | indent 2 }}
---
{{- end -}}