apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-router.fullname" . }}-cfg
  labels:
    {{- include "kube-router.labels" . | nindent 4 }}
data:
  cni-conf.json: |
    {{- .Values.kubeRouter.cni.config | nindent 4 }}