{{- if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "kube-router.fullname" . }}
  labels:
    {{- include "kube-router.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "kube-router.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: metrics
{{- end }}