{{- if eq .Values.kind "Deployment" }}
{{- if .Values.persistence.enabled }}
{{ $error := required "With Deployment and persistence.enabled, a volume named \"netwox-media-files\" should be set via .Values.extraVolumes" .Values.extraVolumes }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{ . | toYaml | trim | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
{{ include "netbox.common" . | indent 2 }}
{{- end }}
