{{- if .Values.extraSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.fullname" . }}-secret
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.extraSecrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
