{{- if .Values.initializers  }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "netbox.initializersConfigName" . | quote }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.initializers }}
  {{ $key }}: |
    {{ $value | indent 4 | trim }}
{{- end }}
{{- end }}
