{{- if eq .Values.kind "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
    {{ . | toYaml | trim | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.statefulSet.replicaCount }}
  serviceName: 'netbox'
{{ include "netbox.common" . | indent 2 }}
{{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
{{- if .Values.persistence.customClaims }}
  {{ .Values.persistence.customClaims | toYaml | nindent 2 }}
{{- else }}
  - spec:
      accessModes:
      {{- range .Values.persistence.accessModes }}
        - {{ . | quote }}
      {{- end }}
      resources:
        requests:
          storage: "{{.Values.persistence.size }}"
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}
    {{- end }}
    metadata:
      name: netbox-media-files
      labels:
        {{- include "netbox.labels" . | nindent 8 }}
{{- end }}
{{- end }}
{{- end }}
