{{- if not .Values.superuserSkip }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbox.superuser.secretName" . }}
  labels:
    {{- include "netbox.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
data:
  SUPERUSER_NAME: {{ .Values.superuser.name | b64enc | quote }}
  SUPERUSER_EMAIL: {{ .Values.superuser.email | b64enc | quote }}
{{- if .Values.superuser.password }}
  SUPERUSER_PASSWORD: {{ .Values.superuser.password | b64enc | quote }}
{{- else }}
  SUPERUSER_PASSWORD: {{ randAlphaNum 14 | b64enc | quote }}
{{- end }}
{{- if .Values.superuser.apiToken }}
  SUPERUSER_API_TOKEN: {{ .Values.superuser.apiToken | b64enc | quote }}
{{- else }}
  SUPERUSER_API_TOKEN: {{ randAlphaNum 40 | b64enc | quote }}
{{- end }}
{{- end }}
