name: Release Charts

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # https://github.com/helm/helm/issues/8036
      # https://github.com/helm/chart-releaser-action/issues/74
      - name: Checkout repositories for dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami

      - name: Run CI script if present
        run: |
          for chart in charts/*; do
            [ -e "$chart" ] || continue

            if [ -f "$chart/ci.sh" ]; then
              cd "$chart"
              ./ci.sh ${{ github.event.client_payload.ref }}
              cd - > /dev/null
            fi
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.1.0
        env:
          CR_TOKEN: '${{ secrets.CR_TOKEN }}'
        with:
          charts_repo_url: https://charts.enix.io/
